"""MSSP 补充材料：由结果文件直接生成 Table S1–S7（不含手写数字）。"""
import os as _os
_ROOT = _os.environ.get("CNS_ROOT", _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__))))
_PAPERB_CODE = _os.environ.get("PAPERB_CODE", _os.path.join(_ROOT, "external/paperB_code"))
_PAPERB_RESULTS = _os.environ.get("PAPERB_RESULTS", _os.path.join(_ROOT, "external/paperB_results"))
_CWRU40 = _os.environ.get("CWRU40_DIR", _os.path.join(_ROOT, "data/cwru_12k_de"))
_CWRU16 = _os.environ.get("CWRU16_DIR", _os.path.join(_ROOT, "data/cwru_16"))
_PU = _os.environ.get("PU_DIR", _os.path.join(_ROOT, "data/paderborn"))
_JNU = _os.environ.get("JNU_DIR", _os.path.join(_ROOT, "data/jnu"))
_JNU_RAW = _os.environ.get("JNU_RAW_DIR", _JNU)
import json, csv, collections, pathlib, re
R = pathlib.Path((_ROOT + "/results")); OUT = pathlib.Path((_ROOT + "/supplement" + "/MSSP_SUPPLEMENT.md"))
J = lambda f: json.load(open(R / f)); CW = {0: "Normal", 1: "IR", 2: "OR", 3: "Ball"}
L = ["# Supplementary material", "", "> Generated by `code/build_supplement.py` from the result files named in each caption; no number is typed by hand.", ""]
# S1
rows = list(csv.DictReader(open(R / "cwru40_file_map.csv", encoding="utf-8")))
L += ["## Table S1. CWRU file-to-split map (40-file split, split_seed 42)", "", "| file | CWRU file | class | size | load (hp) | split | windows | in 16-file subset |", "|---|---|---|---|---|---|---|---|"]
L += [f"| {r['file_id']} | {r['cwru_file']} | {r['cls']} | {r['fault_size_in']} | {r['motor_load_hp']} | {r['split_40file']} | {r['windows']} | {r['in_16file_subset']} |" for r in rows]
# S2
c = J("collapse_defs_sensitivity.json")
L += ["", "## Table S2. Collapse definitions: agreement across the five noise realizations and threshold sensitivity (−8 dB)", "",
      "| experiment | architecture | n | dominant class identical in 5/5 realizations | collapse events (concentration ≥ 0.90) |", "|---|---|---|---|---|"]
for k, v in c.items():
    if k == "non_unanimous_instances": continue
    for m, x in v["per_model"].items(): L.append(f"| {k} | {m} | {x['n']} | {x['unanimous']} | {x['event_090']} |")
L += ["", "Instances whose dominant class differed between realizations (both aggregation orders shown):", "", "| instance | per-realization dominant class | mean of per-realization maxima | maximum of mean distribution | dominant class (both orders) |", "|---|---|---|---|---|"]
PU = ["Healthy", "OR", "IR"]
for x in c["non_unanimous_instances"]:
    L.append(f"| PU {x['arm']} {x['model']} s{x['seed']} | {', '.join(PU[t] for t in x['tops'])} | {x['conc_mean_of_max']:.3f} | {x['max_of_mean_dist']:.3f} | {x['dominant_mode']} / {x['class_of_mean_dist']} |")
# S3
e5 = J("e5_size_id.json"); draws = {}
for r in e5:
    for k, (f, n) in r["files"].items(): draws.setdefault((r["draw"], k), f)
L += ["", "## Table S3. E5 file draws (one recording per class and size in each draw; `e5_size_id.json`, field `files`)", "", "| slot | draw 0 | draw 1 | draw 2 |", "|---|---|---|---|"]
for k in sorted({k for _, k in draws}): L.append(f"| {k} | " + " | ".join(draws.get((d, k), "—") for d in (0, 1, 2)) + " |")
# S4
tl = (R / "PREREG_TIMELINE.md").read_text(); tab = [l for l in tl.splitlines() if l.startswith("|")]
L += ["", "## Table S4. Preregistration timeline (file modification times on the local file system; hashes in `registry/`)", "", "The hashes show that each preregistration was not modified after it was registered; they do not prove to a third party when it was written.", ""] + tab
# S5
p = J("pu_seen_reanalysis_summary.json")
L += ["", f"## Table S5. PU: dominant class at −8 dB on bearings seen in training versus all test bearings ({p['instances_same_target_seen_vs_all']} instances unchanged)", "",
      "| block | arm | architecture | seen bearings | all bearings | clean accuracy, seen | clean accuracy, unseen fault bearings |", "|---|---|---|---|---|---|---|"]
fmt = lambda d: ", ".join(f"{k} {v}" for k, v in sorted(d.items(), key=lambda t: -t[1]))
for k, v in p["cells"].items():
    b, a, m = k.split("|"); L.append(f"| {b} | {a} | {m} | {fmt(v['seen_targets'])} | {fmt(v['all_targets'])} | {v['seen_clean_acc']:.3f} | {v['unseen_clean_acc']:.3f} |")
# S6
S = J("wp5b2_summary.json")["cells"]
L += ["", "## Table S6. Selective classification under rule B2 at −8 dB, by training condition and dataset (post hoc, WP5b v2)", "",
      "Coverage = share of windows accepted (mean over instances). Pooled risk = accepted errors / accepted windows over all instances; undefined when nothing is accepted. Risk at 5% = error rate among the 5% most confident windows (ties resolved by expected risk); risk at 100% = error rate over all windows.", "",
      "| population | architecture | n | coverage | pooled risk | instances with risk defined | risk at 5% | risk at 100% |", "|---|---|---|---|---|---|---|---|"]
order = ["CWRU_clean_F1F2", "CWRU40_clean_F1", "CWRU16_clean_F2_best", "CWRU16_clean_F2_final", "CWRU16_noisetrained_F3_best", "CWRU16_noisetrained_F3_final", "PU_all"]
for pop in order:
    for k in sorted(k for k in S if k.split("|")[0] == pop):
        x = S[k]["-8.0"]; pr = "undefined" if x["risk_pooled"] is None else f"{x['risk_pooled']:.4f}"
        cov = f"{x['coverage']:.4f}" if x["coverage"] >= 1e-3 else f"{x['coverage']:.2e}"
        L.append(f"| {pop} | {k.split('|')[1]} | {x['n']} | {cov} | {pr} | {x['n_risk_defined']}/{x['n']} | {x['rc'][0]:.4f} | {x['rc'][-1]:.4f} |")
# S7
L += ["", "## Table S7. Dominant class and collapse events at −8 dB: original run and fixed-initialization confirmation (C-INIT)", "",
      "Dominant class = most frequent class over the five noise realizations; collapse event = mean concentration ≥ 0.90.", "",
      "| experiment | run | architecture | cell | dominant class | collapse events |", "|---|---|---|---|---|---|"]
for exp, runs, key, cells, models in (("2 × 2", (("original", J("arm2x2.json") + J("arm2x2_lt.json")), ("C-INIT", J("cinit_2x2.json"))), "arm", ["C007_R11", "C007_R31", "CALL_R11", "CALL_R31"], ["wdcnn", "drsn", "lstm", "cnn1d"]),
                                      ("E5", (("original", e5), ("C-INIT", J("cinit_e5.json"))), "set", ["S007", "S014", "S021", "S007+014", "S007+021", "S014+021", "S_ALL"], ["wdcnn", "drsn", "lstm"])):
    for m in models:
        for run, d in runs:
            for cl in cells:
                rs = [r for r in d if r["model"] == m and r[key] == cl]
                if not rs: continue
                dc = collections.Counter(CW[r["observed"]["-8.0"]["top_mode"]] for r in rs); ev = sum(r["observed"]["-8.0"]["conc_mean"] >= 0.9 for r in rs)
                L.append(f"| {exp} | {run} | {m} | {cl} | {fmt(dc)} | {ev}/{len(rs)} |")
OUT.write_text("\n".join(L) + "\n"); print(len(L), "lines")
